# Generated by Django 4.2.15 on 2024-09-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlisted_by", to="auctions.auctionlisting"
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fashion", "Fashion"),
                    ("Toys", "Toys"),
                    ("Electronics", "Electronics"),
                    ("Home", "Home"),
                    ("Books", "Books"),
                    ("Sports", "Sports"),
                    ("Music", "Music"),
                    ("Art", "Art"),
                    ("Collectibles", "Collectibles"),
                    ("Automotive", "Automotive"),
                    ("Jewelry", "Jewelry"),
                    ("Health and Beauty", "Health and Beauty"),
                    ("Food and Drink", "Food and Drink"),
                    ("Travel", "Travel"),
                    ("Services", "Services"),
                    ("Education", "Education"),
                    ("Garden & Outdoor", "Garden & Outdoor"),
                    ("Gaming", "Gaming"),
                    ("Furniture", "Furniture"),
                    ("Pets", "Pets"),
                    ("Technology", "Technology"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=64,
            ),
        ),
    ]
